FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

# install python 3.7 and pip
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        software-properties-common \
        pkg-config \
        rsync \
        curl \
        git \
        unzip \
        zip \
        zlib1g-dev \
        wget \
        vim \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        python3.7 python3.7-dev python3-pip python3.7-venv \
    && python3.7 -m pip install pip --upgrade \
    && python3.7 -m pip install six numpy wheel mock 



RUN apt-get install libsm6 -y
RUN apt-get install libxrender1 -y
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get install libgl1 -y
#RUN cat /etc/apt/sources.list
RUN python3.7 -m pip install setuptools
RUN python3.7 -m pip install tensorflow==1.15
RUN python3.7 -m pip install tensorflow-gpu==1.15
RUN python3.7 -m pip install keras-applications==1.0.8
RUN python3.7 -m pip install keras-preprocessing==1.1.2
RUN python3.7 -m pip install keras==2.2.4
RUN python3.7 -m pip install opencv-python==3.4.5.20
RUN python3.7 -m pip install numpy
RUN python3.7 -m pip install protobuf==3.20.1
ruN python3.7 -m pip install h5py==2.10.0 --force-reinstall